version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/audit-checklist8200-task-new:2"
        LoadBalancerInfo:
          ContainerName: "audit-checklist02"
          ContainerPort: "8200"
        PlatformVersion: "LATEST"
